# Generated by Django 3.0.8 on 2020-07-18 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BgFileToolModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('file', models.FileField(upload_to='layers')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'BG File',
                'verbose_name_plural': 'BG File',
                'db_table': 'tbl_file_data',
                'ordering': ('-created_at',),
            },
        ),
    ]
